### PR TITLE
Make it work in no_std environment

### LINKED ISSUE #201: Can't compile v0.10.0 in the `no_std` environment
The following code compiles with the `derive_builder` crate v0.9.0:

```rust
#![no_std]

#[macro_use]
extern crate derive_builder;

extern crate alloc;

#[derive(Builder)]
#[builder(no_std)]
struct Foo {
    bar: i32,
}
```

However, it can't compile with v0.10.0, even without the default features, emitting the following errors:

```
   Compiling foo v0.1.0 (/tmp/tmp.obTGIdHacx/foo)
error[E0433]: failed to resolve: use of undeclared crate or module `std`
 --> src/lib.rs:8:10
  |
8 | #[derive(Builder)]
  |          ^^^^^^^ use of undeclared crate or module `std`
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `String` in this scope
 --> src/lib.rs:8:10
  |
8 | #[derive(Builder)]
  |          ^^^^^^^ not found in this scope
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
  |
9 | use alloc::string::String;
  |

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `foo`

To learn more, run the command again with --verbose.
```

Something depends on the `std` crate.

### PR DESCRIPTION
**Pull request by andy128k**
Closes #201

### CODE REVIEW

**Comment by TedDriggs** [comment]
What happens in environments where allocations are impossible? Would this compile and then fail if someone tried to construct that variant?

**Comment by andy128k** [comment]
It will not compile. The same as it is in `0.9.0`.
