### ISSUE TITLE
Can't compile v0.10.0 in the `no_std` environment

### ISSUE THREAD

**Issue by toku-sa-n** [colin-kiegel/rust-derive-builder#201]
The following code compiles with the `derive_builder` crate v0.9.0:

```rust
#![no_std]

#[macro_use]
extern crate derive_builder;

extern crate alloc;

#[derive(Builder)]
#[builder(no_std)]
struct Foo {
    bar: i32,
}
```

However, it can't compile with v0.10.0, even without the default features, emitting the following errors:

```
   Compiling foo v0.1.0 (/tmp/tmp.obTGIdHacx/foo)
error[E0433]: failed to resolve: use of undeclared crate or module `std`
 --> src/lib.rs:8:10
  |
8 | #[derive(Builder)]
  |          ^^^^^^^ use of undeclared crate or module `std`
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `String` in this scope
 --> src/lib.rs:8:10
  |
8 | #[derive(Builder)]
  |          ^^^^^^^ not found in this scope
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
  |
9 | use alloc::string::String;
  |

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `foo`

To learn more, run the command again with --verbose.
```

Something depends on the `std` crate.

**Comment by TedDriggs** [comment]
I believe the error is coming from the `FooBuilderError` generated [here](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder_core/src/builder.rs#L222), which includes a `String` as a field in one of its enum variants.

On the crate side, there appear to be three things going on here:

1. We shouldn't generate the `ValidationError(String)` variant for a builder without a user-provided validation function.
2. We shouldn't assume that `String` will mean `String`
3. I'm not sure we even need `#[builder(no_std)]` any more; we might want to deprecate it.

@toku-sa-n if you want to get rid of the compile error without waiting for 0.10.1, you should be able to set `#[builder(build_fn(error = "YourOwnType"))]` as shown in [this example](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/examples/custom_error.rs). That would bypass the generation of the problematic error enum altogether.

@andy128k is there a reason we unconditionally emit the `ValidationError` variant? It seems that we could gate that on the inclusion of a `build_fn(validate = "...")` being set.

**Comment by andy128k** [comment]
Fallible defaults set via `#[builder(default = "self.default_field()?")]` is a reason why it is hard to detect if `ValidationError` is even needed.

**Comment by toku-sa-n** [comment]
Still, this problem doesn't seem to be solved. See https://stackoverflow.com/questions/67189725/why-can-my-no-std-program-compile-even-if-it-depends-on-std-somehow.
From the comment by Masklinn
> here derive-builder (core) depends on darling which depends on darling_core which depends on ident_case.. which depends on std. Therefore cargo tries to pull in std.

**Comment by TedDriggs** [comment]
I believe I've figured out the root cause.

In 0.9.0, `derive_builder` was itself the proc-macro crate, and it depended on `derive_builder_core` which did most of the work and relied on `std` being present. In the move to 0.10.0, we created `derive_builder_macro` to be the proc-macro crate so that `derive_builder` could export other things (e.g. `UninitializedFieldError`). Our mistake was leaving a direct dependency from `derive_builder` to `derive_builder_core`.

Assuming that's correct, the fix is to move `UninitializedFieldError` out of `derive_builder_core`, so that `derive_builder` only depends on `derive_builder_macro`. Testing this locally, that does seem to work.

@toku-sa-n, I couldn't get `rustup target add x86_64_unknown_uefi` to work on my Mac so I tested with `armv7a-none-eabi` Can you please try a build using the Cargo.toml dependency line below and let me know if it works?

```toml
derive_builder = { git = "https://github.com/colin-kiegel/rust-derive-builder", branch = "no_std" }
```

**Comment by toku-sa-n** [comment]
I'm happy to say that I can build my project with the `derive_builder` crate on the `no_std` branch (and `default-features = false`).

**Comment by TedDriggs** [comment]
Excellent! I'd like to keep the test @andy128k added, but I can't figure out why it worked in CI when he published it and now causes the build to fail. I may need to temporarily remove it to get v0.10.2 live so you can stop using a branch dependency.

**Comment by chanced** [comment]
I'm running into this in 0.12.0

**Comment by chanced** [comment]
Would it be better if I created a new issue rather than resurrecting this one?

I can't expand the macro:

```
 cargo expand -p navajo jose::Claims
    Checking navajo v0.0.1 (/Users/chance/dev/navajo/navajo)
error[E0433]: failed to resolve: use of undeclared crate or module `std`
 --> navajo/src/jose/claims.rs:8:63
  |
8 | #[derive(Debug, PartialEq, Eq, Serialize, Clone, Deserialize, Builder, Default)]
  |                                                               ^^^^^^^ use of undeclared crate or module `std`
  |
  = note: this error originates in the derive macro `Builder` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> navajo/src/jose/validator.rs:12:24
   |
12 | #[derive(Debug, Clone, Builder)]
   |                        ^^^^^^^ use of undeclared crate or module `std`
   |
   = note: this error originates in the derive macro `Builder` (in Nightly builds, run with -Z macro-backtrace for more info)
   ```

**Comment by TedDriggs** [comment]
> Would it be better if I created a new issue rather than resurrecting this one?

Yes.

**Comment by TedDriggs** [comment]
A new issue would be better.
________________________________

**Comment by chanced** [comment]
Done, #285
