### PR TITLE
Only generate ValidationError when needed

### LINKED ISSUE #201: Can't compile v0.10.0 in the `no_std` environment
The following code compiles with the `derive_builder` crate v0.9.0:

```rust
#![no_std]

#[macro_use]
extern crate derive_builder;

extern crate alloc;

#[derive(Builder)]
#[builder(no_std)]
struct Foo {
    bar: i32,
}
```

However, it can't compile with v0.10.0, even without the default features, emitting the following errors:

```
   Compiling foo v0.1.0 (/tmp/tmp.obTGIdHacx/foo)
error[E0433]: failed to resolve: use of undeclared crate or module `std`
 --> src/lib.rs:8:10
  |
8 | #[derive(Builder)]
  |          ^^^^^^^ use of undeclared crate or module `std`
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `String` in this scope
 --> src/lib.rs:8:10
  |
8 | #[derive(Builder)]
  |          ^^^^^^^ not found in this scope
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
  |
9 | use alloc::string::String;
  |

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `foo`

To learn more, run the command again with --verbose.
```

Something depends on the `std` crate.

### PR DESCRIPTION
**Pull request by TedDriggs**
Custom validation errors are converted to strings if the deriving struct doesn't specify a type for the errors returned by the `build` method. This variant was generated even when it wasn't needed, resulting in a reference to `String` that broke no_std.

This change only emits that variant when `build_fn(validate = "...")` is set **and** `build_fn(error = "...")` is not set. This means no_std will work in the simple case with no additional meta items needed.

Fixes #201

### CODE REVIEW

**Comment by TedDriggs** [comment]
@andy128k please take a look

**Comment by andy128k** [comment]
This may break a compatibility with a code where custom validation is not provided but a field is annotated as `#[builder(default = "self.default_field()?")]` and `default_field()` returns `Result<_, String>`.

**Comment by TedDriggs** [comment]
The example now calls that out with the phantom_validate function.

**Comment by andy128k** [comment]
Another option is not to generate `ValidationError` at all and advice users to do `#[builder(build_fn(error = "Box<dyn std::error::Error>"))]`.

**Comment by TedDriggs** [comment]
I have a preference for continuing to generate the variant in the case that a validation function is provided, as that avoids making the use of `validate` force a change right away. Also, I don't think `String` implements `std::error::Error`, so that wouldn't work for anyone who had been using `String` before.

**Comment by andy128k** [comment]
`String` does not implement an `Error` trait but still [works well](https://doc.rust-lang.org/stable/std/string/struct.String.html#impl-From%3CString%3E-6) with `Box<dyn Error>`.

**Comment by TedDriggs** [comment]
Today I learned. I’m still inclined to preserve the 0.10.0 decision of using String for the error type in the generated case and omitting it if we don’t need the variant. I don’t love that it’s “magical” but I really don’t want to break people using `validate` more

**Comment by andy128k** [comment]
Version 0.9.0 emitted build method like `fn build(self) -> Result<T, ::alloc::string::String>` and this was acceptable in `no_std` environment. So, probably `ValidationError` could use `alloc::string::String` too?

**Comment by TedDriggs** [comment]
Went with #204 instead
